### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by DwainZwerg**
Translation to German & categorization of Aegis

### CODE REVIEW

**Comment by ImranR98** [comment]
Your JSON is missing commas everywhere.
Use https://jsonlint.com/ to verify JSON before committing.

**Comment by DwainZwerg** [comment]
I will correct it.

**Comment by NicholasFlamy** [comment]
How do you switch languages on the site? I think a button would be useful.

**Comment by ImranR98** [comment]
@NicholasFlamy it will use wherever language your system is on

**Comment by NicholasFlamy** [comment]
> @NicholasFlamy it will use wherever language your system is on

Maybe a manual drop down on the website so you can override it would be nice. Both for testing and for anyone who wants to read it in a different language than their system language. (For example someone with a system language that isn't fully translated so they can switch to English if they know English.)

**Pull request closed without merging**
