### PR TITLE
a few complex app configs

### PR DESCRIPTION
**Pull request by boredsquirrel**
These are all either 3rd party F-Droid repos, or for Briar a direct website download

I added icons too, but found none for Mulch. Anyone know how to get the icons that are shipped in APKs in a 3rd party F-Droid repo?

### CODE REVIEW

**Comment by DwainZwerg** [comment]
Where is https://github.com/Catfriend1/syncthing-android a complex config?

**Comment by boredsquirrel** [comment]
I would like to make an exception, as "Syncthing Fork" is the only one currently maintained. Is that okay? Otherwise I remove it

**Comment by boredsquirrel** [comment]
removed it and the other version too. I see I had some cleanups in there too, are they fine?

**Comment by ImranR98** [comment]
Sorry, shouldn't have merged this. Needed to revert it. Looks like you're deleting a bunch of things that shouldn't be?

**Pull request merged**
