### PR TITLE
small improvements …

### PR DESCRIPTION
**Pull request by DwainZwerg**
… for Firefox Nightly (Version detection with consideration of the hour of release), for SchildiChat (added "(SpiritCroc)" to the last variant; added description & icon), for AppVerifier, Instagram & Mull (fixes of icon URLs), for Pixiv (add icon), for Mozilla Firefox (intermediate versions see https://github.com/ImranR98/Obtainium/issues/1847#issuecomment-2365362953), for Firefox Focus/Klar (intermediate versions see https://github.com/ImranR98/Obtainium/issues/1847#issuecomment-2365362953). Translation of the request modal.

### CODE REVIEW

**Comment by ImranR98** [comment]
@DwainZwerg for some reason the Firefox configs don't work for me. I'm not familiar with some of the RegEx syntax you've used (`(?:(d+).)?(?:(d+).)?(?:(d+).d+)+/$`) but it works if I use this: `[0-9]+\.[0-9]+(\.[0-9]+)?`

**Comment by Hamster45105** [comment]
@ImranR98 could you share the config link please? Neither your regex nor the current one on the website works for me at the moment.

**Comment by ImranR98** [comment]
https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22org.mozilla.firefox%22%2C%22url%22%3A%22https%3A%2F%2Fdownload.cdn.mozilla.net%2Fpub%2Ffenix%2Freleases%2F%22%2C%22author%22%3A%22download.cdn.mozilla.net%22%2C%22name%22%3A%22Firefox%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B)%2B%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Atrue%7D%2C%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22android%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%2C%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22fenix-(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B)%2B-android-arm64-v8a%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B)%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Gecko-based%20browser%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D

**Comment by Hamster45105** [comment]
This doesn't work because it is not picking up 130.0.1 which is exactly what the update to the regexes was meant to fix (https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/155#discussioncomment-10715434).

Not sure what the solution is here.

**Comment by DwainZwerg** [comment]
@ImranR98 @Hamster45105 I knowledged it since I hvbe added. It is because I removed the spaßeshalber because the Jones was brocken. Now the Regex is brocken. If you have an idea to fix it, fiel free to fix. I'm on a exhibition Till Sundqy, so I couldn't fix.

**Comment by DwainZwerg** [comment]
@ImranR98 @Hamster45105 I have edited the old message (this message is just to make sure you have received the edited message).

**Comment by DarkCrypt** [comment]
Try this: `[0-9]+.[0-9]+\.[0-9]+`

**Comment by DwainZwerg** [comment]
The problem is that for the intermediate versions we need `(?:(\d+)\.)?(?:(\d+)\.)?(?:(\d+)\.\d+)+/$` (1. intermediate link), `android/$` (2. intermediate link) and `fenix-(?:(\d+)\.)?(?:(\d+)\.)?(?:(\d+)\.\d+)+-android-arm64-v8a/$` (3rd intermediate link). The other configuration was the old configuration, which could not do intermediate versions. The new version could do it in Obtainium, but the json of the website doesn't like the many slashes. I then removed the slashes, as I have done many times before for other configs for the website. So far, Obtainium has not complained about the missing slashes, but has added them itself. But this time it didn't work.

I am also not the great JSon expert who can tell you how to enter the configuration into the json file in any other way.

**Comment by DarkCrypt** [comment]
I already knew about the struggle with intermediate versions. I didn't know about the website slash issue. I would be no use trying to contribute to the website because I know nothing about Json.

The ReGex I posted above should work based on ReGex sites (ReGex101, etc.) but I've noticed sometimes those results don't work in Obtainium either. I don't know any other way to test besides waiting for Firefox to put out updates. So I'm going to wait and see if it does work otherwise I'll switch to your fix.

I do have a new idea for the "Get it on Obtainium" button but I'm undecided if I should bother.

**Pull request merged**
