### PR TITLE
Create com.collaboraoffice.libreoffice.snapshot

### PR DESCRIPTION
**Pull request by DwainZwerg**

### CODE REVIEW

**Comment by DwainZwerg** [comment]
How do I mark which version is which version?

**Comment by DwainZwerg** [comment]
@ImranR98 I've one config for each arch. Ho could I mark wich config is for which arch?

**Comment by ImranR98** [comment]
You can add an `"altLabel"` property to each config.

**Comment by ImranR98** [comment]
Also the first config is always the "main" one (see Syncthing on the website for an example of how the main config is shown compared to the alternative ones). So it's best to put the armv8 config at the top (most common).

**Comment by DwainZwerg** [comment]
@ImranR98 now finished

**Comment by DwainZwerg** [comment]
Sorry, there is still a json error somewhere

**Comment by DwainZwerg** [comment]
If anyone has any idea what the error in the json is, please let me know or fork my project and fix the error.

**Comment by ImranR98** [comment]
This should work:

```json
{
    "configs": [
        {
            "id": "com.collaboraoffice.libreoffice.snapshot",
            "url": "https://collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot",
            "author": "Collabora Productivity",
            "name": "Collabora Office",
            "preferredApkIndex": 0,
            "additionalSettings": "{\"intermediateLink\":[],\"customLinkFilterRegex\":\"\",\"filterByLinkText\":false,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":true,\"versionExtractWholePage\":true,\"requestHeader\":[{\"requestHeader\":\"User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36\"}],\"defaultPseudoVersioningMethod\":\"APKLinkHash\",\"trackOnly\":false,\"versionExtractionRegEx\":\"\",\"matchGroupToUse\":\"\",\"versionDetection\":false,\"useVersionCodeAsOSVersion\":false,\"apkFilterRegEx\":\"collabora-office-mobile-[0-9]+\\\\.[0-9]+-snapshot-arm64-[A-Za-z0-9]+-[0-9]{4}-[0-9]{2}-[0-9]{2}\\\\.apk\",\"invertAPKFilter\":false,\"autoApkFilterByArch\":true,\"appName\":\"\",\"shizukuPretendToBeGooglePlay\":false,\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\",\"supportFixedAPKURL\":false}",
            "pinned": false,
            "releaseDate": null,
            "changeLog": null,
            "overrideSource": "HTML",
            "allowIdChange": false,
            "altLabel": "arm64 v8a"
        },
        {
            "id": "com.collaboraoffice.libreoffice.snapshot",
            "url": "https://collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot",
            "author": "Collabora Productivity",
            "name": "Collabora Office",
            "preferredApkIndex": 0,
            "additionalSettings": "{\"intermediateLink\":[],\"customLinkFilterRegex\":\"\",\"filterByLinkText\":false,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":true,\"versionExtractWholePage\":true,\"requestHeader\":[{\"requestHeader\":\"User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36\"}],\"defaultPseudoVersioningMethod\":\"APKLinkHash\",\"trackOnly\":false,\"versionExtractionRegEx\":\"\",\"matchGroupToUse\":\"\",\"versionDetection\":false,\"useVersionCodeAsOSVersion\":false,\"apkFilterRegEx\":\"collabora-office-mobile-[0-9]+\\\\.[0-9]+-snapshot-armeabi-[A-Za-z0-9]+-[0-9]{4}-[0-9]{2}-[0-9]{2}\\\\.apk\",\"invertAPKFilter\":false,\"autoApkFilterByArch\":true,\"appName\":\"\",\"shizukuPretendToBeGooglePlay\":false,\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\",\"supportFixedAPKURL\":false}",
            "pinned": false,
            "releaseDate": null,
            "changeLog": null,
            "overrideSource": "HTML",
            "allowIdChange": false,
            "altLabel": "armeabi v7a"
        },
        {
            "id": "com.collaboraoffice.libreoffice.snapshot",
            "url": "https://collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot",
            "author": "Collabora Productivity",
            "name": "Collabora Office",
            "preferredApkIndex": 0,
            "additionalSettings": "{\"intermediateLink\":[],\"customLinkFilterRegex\":\"\",\"filterByLinkText\":false,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":true,\"versionExtractWholePage\":true,\"requestHeader\":[{\"requestHeader\":\"User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36\"}],\"defaultPseudoVersioningMethod\":\"APKLinkHash\",\"trackOnly\":false,\"versionExtractionRegEx\":\"\",\"matchGroupToUse\":\"\",\"versionDetection\":false,\"useVersionCodeAsOSVersion\":false,\"apkFilterRegEx\":\"collabora-office-mobile-[0-9]+\\\\.[0-9]+-snapshot-x86-[0-9]{4}-[0-9]{2}-[0-9]{2}\\\\.apk\",\"invertAPKFilter\":false,\"autoApkFilterByArch\":true,\"appName\":\"\",\"shizukuPretendToBeGooglePlay\":false,\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\",\"supportFixedAPKURL\":false}",
            "pinned": false,
            "releaseDate": null,
            "changeLog": null,
            "overrideSource": "HTML",
            "allowIdChange": false,
            "altLabel": "x86"
        },
        {
            "id": "com.collaboraoffice.libreoffice.snapshot",
            "url": "https://collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot",
            "author": "Collabora Productivity",
            "name": "Collabora Office",
            "preferredApkIndex": 0,
            "additionalSettings": "{\"intermediateLink\":[],\"customLinkFilterRegex\":\"\",\"filterByLinkText\":false,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":true,\"versionExtractWholePage\":true,\"requestHeader\":[{\"requestHeader\":\"User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36\"}],\"defaultPseudoVersioningMethod\":\"APKLinkHash\",\"trackOnly\":false,\"versionExtractionRegEx\":\"\",\"matchGroupToUse\":\"\",\"versionDetection\":false,\"useVersionCodeAsOSVersion\":false,\"apkFilterRegEx\":\"collabora-office-mobile-[0-9]+\\\\.[0-9]+-snapshot-x86_64-[0-9]{4}-[0-9]{2}-[0-9]{2}\\\\.apk\",\"invertAPKFilter\":false,\"autoApkFilterByArch\":true,\"appName\":\"\",\"shizukuPretendToBeGooglePlay\":false,\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\",\"supportFixedAPKURL\":false}",
            "pinned": false,
            "releaseDate": null,
            "changeLog": null,
            "overrideSource": "HTML",
            "allowIdChange": false,
            "altLabel": "x86_64"
        }
    ],
    "icon": "https://www.collaboraoffice.com/wp-content/uploads/2022/03/cropped-collabora-productivity-nav-icon.png",
    "description": {
        "en": "LTS Support and Services for Libre Office.",
        "de": "LTS-Support und -Service für Libre Office."
    },
    "categories": [
        "document_and_pdf_viewer",
        "image_manipulation"
    ]
}
```

**Pull request merged**
